services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # 注册 DataFixtures 类
  Tourze\GaNetBundle\DataFixtures\:
    resource: '../../DataFixtures/*'
    tags: [ 'doctrine.fixture.orm' ]